load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "main",
    srcs = ["main.ccp"],
    deps = [
        ":TBD",
        "//api:main",
        "//auth:main",
        "//lib:main",
        "//structs:main",
    ],
)